### ISSUE TITLE
提示 ERR_INVALID_ARG_TYPE 错误

### ISSUE THREAD

**Issue by wangzhongjie** [ecfexorg/wx-ding-aes#5]
你好我这边测试提示错误：
ypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, Buffer, TypedArray, or DataView. Received type object
    at Decipheriv.update (internal/crypto/cipher.js:155:11)
    at Object.exports.decrypt (/Users/wzjcool/Documents/tiancai/server/node_modules/wx-ding-aes/dist/aes.js:26:18)
    at Object.exports.decode (/Users/wzjcool/Documents/tiancai/server/node_modules/wx-ding-aes/dist/wx.js:30:34)
    at /Users/wzjcool/Documents/tiancai/server/src/controller/wx.js:32:23
    at Generator.next (<anonymous>)
    at step (/Users/wzjcool/Documents/tiancai/server/app/controller/wx.js:1:191)
    at /Users/wzjcool/Documents/tiancai/server/app/controller/wx.js:1:437
    at new Promise (<anonymous>)
    at /Users/wzjcool/Documents/tiancai/server/app/controller/wx.js:1:99
    at module.exports.ticketAction (/Users/wzjcool/Documents/tiancai/server/src/controller/wx.js:12:23)

**Comment by beary** [comment]
函数`decrypt()`的参数`data`只能为字符串，不能传入对象
